# Generated by Django 4.2.1 on 2023-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plains', max_length=50)),
                ('price', models.FloatField(default=0.05)),
                ('quantity', models.IntegerField(default=0)),
                ('types', models.CharField(default='Basic Land - Plains', max_length=50)),
                ('set', models.CharField(default='DMU', max_length=4)),
                ('collector_number', models.IntegerField(default=262)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('PL', 'Played'), ('HP', 'Heavily Played')], default='NM', max_length=2)),
                ('finish', models.BooleanField(default=False, help_text='Foil or non-foil')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['name', 'price'],
            },
        ),
    ]
