# Generated by Django 4.2.1 on 2023-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_card_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img',
        ),
    ]
